### ISSUE TITLE
How to avoid line break before comparison operator?

### ISSUE THREAD

**Issue by danijar** [google/yapf#1166]
Hi, I'm trying to adopt YAPF for a larger code base and am running into a few edge cases. Is there a configuration option to achieve the following desired output? Thanks!

Actual:

```
long_variable_name = (long_variable_name
    == long_variable_name) and (long_variable_name == 1)
```

Desired:

```
long_variable_name = (
    (long_variable_name == long_variable_name) and (long_variable_name == 1))

# OR

long_variable_name = (
    (long_variable_name == long_variable_name) and
    (long_variable_name == 1))
```

pyproject.toml

```toml
[tool.yapf]
based_on_style = "pep8"
indent_width = 2
allow_multiline_lambdas = true
continuation_align_style = "FIXED"
continuation_indent_width = 4
split_before_closing_bracket = false
split_before_expression_after_opening_paren = true
split_before_first_argument = true
dedent_closing_brackets = false
each_dict_entry_on_separate_line = false
```
