### ISSUE TITLE
Can YAPF prefer more balanced splits for list/dict comprehensions?

### ISSUE THREAD

**Issue by danijar** [google/yapf#1168]
The short line `k: v` looks a bit odd and a line break before the `if` would be more natural. Is there currently a way of doing this in YAPF?

Actual:

```python
donated = {
    k: v
    for k, v in very_long_dict_name.items() if k not in self.copy_keys}
```

Desired:

```python
donated = {
    k: v for k, v in very_long_dict_name.items()
    if k not in self.copy_keys}
```

pyproject.toml

```toml
[tool.yapf]
based_on_style = "pep8"
indent_width = 2
allow_multiline_lambdas = true
continuation_align_style = "FIXED"
continuation_indent_width = 4
dedent_closing_brackets = false
each_dict_entry_on_separate_line = false
spaces_around_power_operator = true
split_before_closing_bracket = false
split_before_expression_after_opening_paren = true
split_before_first_argument = true
split_before_logical_operator = false
```
