### ISSUE TITLE
How to properly indent dicts inside lambda inside function argument list?

### ISSUE THREAD

**Issue by danijar** [google/yapf#1169]
Actual:

```python
batcher = embodied.Batcher(
    sources=[generator] * self.config.batch_size,
    workers=self.config.data_loaders, postprocess=lambda x: {
    **self._convert_inps(x, self.train_devices), 'rng':
    self._next_rngs(self.train_devices)}, prefetch_source=4)
```

Desired:

```python
batcher = embodied.Batcher(
    sources=[generator] * self.config.batch_size,
    workers=self.config.data_loaders,
    postprocess=lambda x: {
        **self._convert_inps(x, self.train_devices),
        'rng': self._next_rngs(self.train_devices)},
    prefetch_source=4)
```

pyproject.toml

```toml
[tool.yapf]
based_on_style = "pep8"
indent_width = 2
allow_multiline_lambdas = true
continuation_align_style = "FIXED"
continuation_indent_width = 4
dedent_closing_brackets = false
each_dict_entry_on_separate_line = false
spaces_around_power_operator = true
split_arguments_when_comma_terminated = true
split_before_closing_bracket = false
split_before_expression_after_opening_paren = true
split_before_first_argument = true
split_before_logical_operator = false
split_before_named_assigns = false
```
