### ISSUE TITLE
Integration with pyproject.toml for Formatting style

### ISSUE THREAD

**Issue by samypr100** [google/yapf#708]
[PEP 518](https://www.python.org/dev/peps/pep-0518/) defines `pyproject.toml` as a configuration file for software packages to use to specify their build dependencies.

Particularly, it provides an alternative to `setup.cfg`.

For example, a section in `pyproject.toml` could look like:
```toml
[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
split_before_logical_operator = true
```

Initially, `yapf` could look for a `pyproject.toml` on the project and determine formatting style settings from that similar to how it does with `setup.cfg`.

This request would be an additional method to the currently supported methods of specifying `yapf` settings. Any chance we could see this in `yapf`?
